def utone(usertone):
	if usertone == "1":
		tone = "Tone: Formal\r\n"
	elif usertone == "2":
		tone = "Tone: Informal\r\n"
	elif usertone == "3":
		tone = "Tone: Optimistic\r\n"
	elif usertone == "4":
		tone = "Tone: Creative\r\n"
	elif usertone == "5":
		tone = "Tone: Friendly\r\n"
	elif usertone == "6":
		tone = "Tone: Professional\r\n"
	elif usertone == "7":
		tone = "Tone: Bold\r\n"
	elif usertone == "8":
		tone = "Tone: Adventurous\r\n"
	elif usertone == "9":
		tone = "Tone: Witty\r\n"
	elif usertone == "10":
		tone = "Tone: Persuasive\r\n"
	elif usertone == "11":
		tone = "Tone: Empathetic\r\n"
	elif usertone == "12":
		tone = "Tone: Conversational\r\n"
	elif usertone == "13":
		tone = "Tone: Questioning\r\n"
	elif usertone == "14":
		tone = "Tone: Assertive\r\n"
	elif usertone == "15":
		tone = "Tone: Directive\r\n"
	elif usertone == "16":
		tone = "Tone: Factual\r\n"
	elif usertone == "17":
		tone = "Tone: Respectful\r\n"
	elif usertone == "18":
		tone = "Tone: Motivating\r\n"
	elif usertone == "19":
		tone = "Tone: Informative\r\n"
	elif usertone == "20":
		tone = "Tone: Flirting\r\n"
	elif usertone == "21":
		tone = "Tone: Sexy\r\n"
	elif usertone == "22":
		tone = "Tone: Loving\r\n"
	elif usertone == "23":
		tone = "Tone: Romantic\r\n"
	elif usertone == "24":
		tone = "Tone: Excited\r\n"
	elif usertone == "25":
		tone = "Tone: Urgent\r\n"
	elif usertone == "26":
		tone = "Tone: Anxious\r\n"
	elif usertone == "27":
		tone = "Tone: Apologetic\r\n"
	elif usertone == "28":
		tone = "Tone: Appreciative\r\n"
	elif usertone == "29":
		tone = "Tone: Bored\r\n"
	elif usertone == "30":
		tone = "Tone: Calm\r\n"
	elif usertone == "31":
		tone = "Tone: Candid\r\n"
	elif usertone == "32":
		tone = "Tone: Cheerful\r\n"
	elif usertone == "33":
		tone = "Tone: Cold\r\n"
	elif usertone == "34":
		tone = "Tone: Concerned\r\n"
	elif usertone == "35":
		tone = "Tone: Courteous\r\n"
	elif usertone == "36":
		tone = "Tone: Critical\r\n"
	elif usertone == "37":
		tone = "Tone: Cruel\r\n"
	elif usertone == "38":
		tone = "Tone: Curious\r\n"
	elif usertone == "39":
		tone = "Tone: Cynical\r\n"
	elif usertone == "40":
		tone = "Tone: Defensive\r\n"
	elif usertone == "41":
		tone = "Tone: Depressed\r\n"
	elif usertone == "42":
		tone = "Tone: Desperate\r\n"
	elif usertone == "43":
		tone = "Tone: Determined\r\n"
	elif usertone == "44":
		tone = "Tone: Diplomatic\r\n"
	elif usertone == "45":
		tone = "Tone: Disappointed\r\n"
	elif usertone == "46":
		tone = "Tone: Disgusted\r\n"
	elif usertone == "47":
		tone = "Tone: Dramatic\r\n"
	elif usertone == "48":
		tone = "Tone: Dreamy\r\n"
	elif usertone == "49":
		tone = "Tone: Eccentric\r\n"
	elif usertone == "50":
		tone = "Tone: Eloquent\r\n"
	elif usertone == "51":
		tone = "Tone: Encouraging\r\n"
	elif usertone == "52":
		tone = "Tone: Enthusiastic\r\n"
	elif usertone == "53":
		tone = "Tone: Excited\r\n"
	elif usertone == "54":
		tone = "Tone: Fearful\r\n"
	elif usertone == "55":
		tone = "Tone: Frustrated\r\n"
	elif usertone == "56":
		tone = "Tone: Funny\r\n"
	elif usertone == "57":
		tone = "Tone: Gloomy\r\n"
	elif usertone == "58":
		tone = "Tone: Happy\r\n"
	elif usertone == "59":
		tone = "Tone: Hesitant\r\n"
	elif usertone == "60":
		tone = "Tone: Hopeful\r\n"
	elif usertone == "61":
		tone = "Tone: Horrific\r\n"
	elif usertone == "62":
		tone = "Tone: Humorous\r\n"
	elif usertone == "63":
		tone = "Tone: Imaginative\r\n"
	elif usertone == "64":
		tone = "Tone: Inspirational\r\n"
	elif usertone == "65":
		tone = "Tone: Judgmental\r\n"
	elif usertone == "66":
		tone = "Tone: Mocking\r\n"
	elif usertone == "67":
		tone = "Tone: Negative\r\n"
	elif usertone == "68":
		tone = "Tone: Nervous\r\n"
	elif usertone == "69":
		tone = "Tone: Patient\r\n"
	elif usertone == "70":
		tone = "Tone: Poetic\r\n"
	elif usertone == "71":
		tone = "Tone: Proud\r\n"
	elif usertone == "72":
		tone = "Tone: Regretful\r\n"
	elif usertone == "73":
		tone = "Tone: Remorseful\r\n"
	elif usertone == "74":
		tone = "Tone: Sarcastic\r\n"
	elif usertone == "75":
		tone = "Tone: Serious\r\n"
	elif usertone == "76":
		tone = "Tone: Snobbish\r\n"
	elif usertone == "77":
		tone = "Tone: Stubborn\r\n"
	elif usertone == "78":
		tone = "Tone: Surprised\r\n"
	elif usertone == "79":
		tone = "Tone: Thankful\r\n"
	elif usertone == "80":
		tone = "Tone: Upset\r\n"
	elif usertone == "81":
		tone = "Tone: Sales\r\n"
	elif usertone == "":
		tone = "Tone: Friendly\r\n"
	return (tone)