# Generated by Django 4.1.3 on 2022-11-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0002_useracc_is_active_useracc_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useracc",
            name="credit",
            field=models.IntegerField(default=0),
        ),
    ]
