# Generated by Django 4.1.3 on 2022-11-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0003_alter_useracc_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("value", models.IntegerField(default=0)),
                ("limited_offer_desc", models.CharField(max_length=150)),
                ("desc1", models.CharField(max_length=150)),
                ("desc2", models.CharField(max_length=150)),
            ],
        ),
    ]
