# Generated by Django 4.1.3 on 2022-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0004_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="packages",
            name="cycle",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="packages",
            name="price",
            field=models.CharField(default="", max_length=10),
        ),
    ]
