# Generated by Django 4.1.3 on 2022-11-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0005_packages_cycle_packages_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packages",
            name="limited_offer_desc",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
