# Generated by Django 4.1.3 on 2022-11-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0006_alter_packages_limited_offer_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="useracc",
            name="package",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
