# Generated by Django 4.1.3 on 2022-11-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0008_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useracc",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
